src/Entity/MeteoData.php
<?php

namespace App\Entity;

use App\Repository\MeteoDataRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MeteoDataRepository::class)]
class MeteoData
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'meteoData')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: 0)]
    private ?string $celsius_temperature = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: 0, nullable: true)]
    private ?string $flcelsius_temperature = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private ?int $pressure = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private ?int $humidity = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 4, scale: 1, nullable: true)]
    private ?float $wind_speed = null;

    #[ORM\Column(type: Types::STRING, length: 10, nullable: true)]
    private ?string $wind_direction = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private ?int $cloudiness = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $icon = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getCelsiusTemperature(): ?string
    {
        return $this->celsius_temperature;
    }

    public function setCelsiusTemperature(string $celsius_temperature): static
    {
        $this->celsius_temperature = $celsius_temperature;

        return $this;
    }

    public function getFlCelsiusTemperature(): ?string
    {
        return $this->flcelsius_temperature;
    }

    public function setFlCelsiusTemperature(?string $flcelsius_temperature): self
    {
        $this->flcelsius_temperature = $flcelsius_temperature;

        return $this;
    }

    public function getPressure(): ?int
    {
        return $this->pressure;
    }

    public function setPressure(?int $pressure): self
    {
        $this->pressure = $pressure;

        return $this;
    }

    public function getHumidity(): ?int
    {
        return $this->humidity;
    }

    public function setHumidity(?int $humidity): self
    {
        $this->humidity = $humidity;

        return $this;
    }

    public function getWindSpeed(): ?float
    {
        return $this->wind_speed;
    }

    public function setWindSpeed(?float $wind_speed): self
    {
        $this->wind_speed = $wind_speed;

        return $this;
    }

    public function getWindDirection(): ?string
    {
        return $this->wind_direction;
    }

    public function setWindDirection(?string $wind_direction): self
    {
        $this->wind_direction = $wind_direction;

        return $this;
    }

    public function getCloudiness(): ?int
    {
        return $this->cloudiness;
    }

    public function setCloudiness(?int $cloudiness): self
    {
        $this->cloudiness = $cloudiness;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(?string $icon): self
    {
        $this->icon = $icon;

        return $this;
    }
    
}

src/Form/MeteoDataType.php
<?php

namespace App\Form;

use App\Entity\Location;
use App\Entity\MeteoData;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MeteoDataType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', null, [
                'widget' => 'single_text',
            ])
            ->add('location', EntityType::class, [
                'class' => Location::class,
                'choice_label' => 'city',
            ])
            ->add('celsius_temperature')
            ->add('flcelsius_temperature', null, [
                'label' => 'Feels like temperature',
            ])
            ->add('pressure')
            ->add('humidity')
            ->add('windSpeed')
            ->add('wind_direction')
            ->add('cloudiness')
            ->add('icon', ChoiceType::class, [
                'choices' => [
                    'sun' => 'bi-sun',
                    'cloud' => 'bi-cloud',
                    'cloud-sun' => 'bi-cloud-sun',
                    'cloud-rain' => 'bi-cloud-rain',
                    'cloud-snow' => 'bi-cloud-snow',
                    'snow' => 'bi-snow',
                    'cloud-lightning' => 'bi-cloud-lightning',
                    'wind' => 'bi-wind',
                    'cloud-fog' => 'bi-cloud-fog',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MeteoData::class,
        ]);
    }
}

src/Controller/MeteoDataController.php
<?php

namespace App\Controller;

use App\Entity\MeteoData;
use App\Form\MeteoDataType;
use App\Repository\MeteoDataRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/meteo/data')]
final class MeteoDataController extends AbstractController
{
    #[Route(name: 'app_meteo_data_index', methods: ['GET'])]
    public function index(MeteoDataRepository $meteoDataRepository): Response
    {
        return $this->render('meteo_data/index.html.twig', [
            'meteo_datas' => $meteoDataRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_meteo_data_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $meteoDatum = new MeteoData();
        $form = $this->createForm(MeteoDataType::class, $meteoDatum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($meteoDatum);
            $entityManager->flush();

            return $this->redirectToRoute('app_meteo_data_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('meteo_data/new.html.twig', [
            'meteo_datum' => $meteoDatum,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_meteo_data_show', methods: ['GET'])]
    public function show(MeteoData $meteoDatum): Response
    {
        return $this->render('meteo_data/show.html.twig', [
            'meteo_datum' => $meteoDatum,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_meteo_data_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, MeteoData $meteoDatum, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MeteoDataType::class, $meteoDatum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            return $this->redirectToRoute('app_meteo_data_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('meteo_data/edit.html.twig', [
            'meteo_datum' => $meteoDatum,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_meteo_data_delete', methods: ['POST'])]
    public function delete(Request $request, MeteoData $meteoDatum, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$meteoDatum->getId(), $request->request->get('_token'))) {
            $entityManager->remove($meteoDatum);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_meteo_data_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/meteo_data/_delete_form.html.twig
<form method="post" action="{{ path('app_meteo_data_delete', {'id': meteo_datum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ meteo_datum.id) }}">
    <div class="button-container">
        <button class="btn btn-danger">Delete</button>
    </div>
</form>

templates/meteo_data/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

    <div class="button-container">
        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    </div>

{{ form_end(form) }}

templates/meteo_data/edit.html.twig
{% extends 'layout_crud.html.twig' %}

{% block title %}Edit MeteoData{% endblock %}

{% block content %}
    <h1>Edit MeteoData</h1>

    {{ include('meteo_data/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="button-container">
        <a href="{{ path('app_meteo_data_index') }}" class="btn btn-secondary me-2">back to list</a>
    </div>

    {{ include('meteo_data/_delete_form.html.twig') }}
{% endblock %}

templates/meteo_data/index.html.twig
{% extends 'layout_crud.html.twig' %}

{% block title %}MeteoData index{% endblock %}

{% block body %}
    <h1>MeteoData index</h1>

    <script>
        function toggleDetails(id) {
            const details = document.getElementById(id);
            details.style.display = details.style.display === 'none' ? 'table-row' : 'none';
        }
    </script>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>City</th>
                <th>Temperature[°C]</th>
                <th>Feels Like[°C]</th>
                <th>Icon</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for meteo_datum in meteo_datas %}
            <tr>
                <td>{{ meteo_datum.id }}</td>
                <td>{{ meteo_datum.date ? meteo_datum.date|date('Y-m-d') : '' }}</td>
                <td>{{ meteo_datum.location.city }}</td>
                <td>{{ meteo_datum.celsiusTemperature }}</td>
                <td>{{ meteo_datum.flcelsiusTemperature }}</td>
                <td><i class="bi-{{ meteo_datum.icon }}"></i></td>
                <td>
                    <div class="button-container">
                        <a href="#" class="btn btn-info me-2" onclick="toggleDetails({{ meteo_datum.id }})">details</a>
                        <a href="{{ path('app_meteo_data_show', {'id': meteo_datum.id}) }}" class="btn btn-secondary me-2">show this</a>
                        <a href="{{ path('app_meteo_data_edit', {'id': meteo_datum.id}) }}" class="btn btn-secondary me-2">edit</a>
                    </div>
                </td>
            </tr>
            <tr id="{{ meteo_datum.id }}" style="display: none;">
                <td colspan="7">
                    <strong>Pressure:</strong> {{ meteo_datum.pressure }} hPa<br>
                    <strong>Humidity:</strong> {{ meteo_datum.humidity }}%<br>
                    <strong>Wind Speed:</strong> {{ meteo_datum.windSpeed }} "m/s"<br>
                    <strong>Wind Direction:</strong> {{ meteo_datum.windDirection }}°<br>
                    <strong>Cloudiness:</strong> {{ meteo_datum.cloudiness }}%<br>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="button-container">
        <a href="{{ path('app_meteo_data_new') }}" class="btn btn-primary">Create new</a>
    </div>
{% endblock %}

templates/meteo_data/new.html.twig
{% extends 'layout_crud.html.twig' %}

{% block title %}New MeteoData{% endblock %}

{% block body %}
    <h1>Create new MeteoData</h1>

    {{ include('meteo_data/_form.html.twig') }}

    <div class="button-container">
        <a href="{{ path('app_meteo_data_index') }}" class="btn btn-secondary me-2">back to list</a>
    </div>
{% endblock %}

templates/meteo_data/show.html.twig
{% extends 'layout_crud.html.twig' %}

{% block title %}MeteoData{% endblock %}

{% block body %}
    <h1>MeteoData</h1>

    <script>
        function toggleDetails(id) {
            const details = document.getElementById(id);
            details.style.display = details.style.display === 'none' ? 'table-row' : 'none';
        }
    </script>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ meteo_datum.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ meteo_datum.date ? meteo_datum.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ meteo_datum.location.city }}</td>
            </tr>
            <tr>
                <th>Temperature</th>
                <td>{{ meteo_datum.celsiusTemperature }}</td>
            </tr>
            <tr>
                <th>Feels Like</th>
                <td>{{ meteo_datum.flCelsiusTemperature }}</td>
            </tr>
            <tr>
                <th>Pressure</th>
                <td>{{ meteo_datum.pressure }}</td>
            </tr>
            <tr>
                <th>Humidity</th>
                <td>{{ meteo_datum.humidity }}</td>
            </tr>
            <tr>
                <th>Wind Speed</th>
                <td>{{ meteo_datum.windSpeed }}</td>
            </tr>
            <tr>
                <th>Wind Direction</th>
                <td>{{ meteo_datum.windDirection }}</td>
            </tr>
            <tr>
                <th>Cloudiness</th>
                <td>{{ meteo_datum.cloudiness }}</td>
            </tr>
            <tr>
                <th>Icon</th>
                <td><i class="bi-{{ meteo_datum.icon }}"></i></td>
            </tr>
        </tbody>
    </table>

    <div class="button-container">
        <a href="{{ path('app_meteo_data_index') }}" class="btn btn-secondary me-2">back to list</a>
        <a href="{{ path('app_meteo_data_edit', {'id': meteo_datum.id}) }}" class="btn btn-secondary me-2">edit</a>
    </div>

    {{ include('meteo_data/_delete_form.html.twig') }}
{% endblock %}